### ISSUE TITLE
run time parameter

### ISSUE THREAD

**Issue by BotMichael** [SimonLarsen/sailmcs#2]
I'm interested in your algorithm. However, I'm confused about the time parameter.
For "-t 10:00", does it mean the software will run for 10 mins or total annealing time is 10 mins?

**Comment by SimonLarsen** [comment]
Hi. The time parameter determines how long the program will run (in wall time) before terminating. The iterative procedure will repeat until the time limit is exceeded, and then return when the current iteration is done.

You may want to check out this repo as well: https://github.com/SimonLarsen/faithmcs. It is a much simpler algorithm based on similar ideas.

**Comment by BotMichael** [comment]
Great! Thank u so much!
